[package]
name = "interest_v4"
edition = "2024.beta"
license = "Apache-2.0"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]
interest_access_control = { r.mvr = "@interest/acl" }

[addresses]
interest_v4 = "0x7"

[dev-dependencies]

[dev-addresses]

[r.mvr]
network = "testnet"
