[package]
name = "tide-amm"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     

[dependencies]

Pyth = { local = "../sui-dependencies/pyth" }
Wormhole = { local = "../sui-dependencies/wormhole" }

interest_access_control = { r.mvr = "@interest/acl" }

[addresses]
tide_amm = "0x0"

[r.mvr]
network = "mainnet"
